services:
  - type: web
    name: ProManage
    env: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true